server:
  port: 9006
spring:
  application:
    name: ten-square-gathering
  cache:
    type: redis
    ehcache:
      config: classpath:ehcache.xml
spring:
  profiles:
    active: dev


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.deluxe: debug

